Repository National-Digital-Twin/federator, pull requests merged in 2025-09, with the labels that each got.

#44 feat(DPAV-1644): add support for JWT access token caching using Redis
  docker/docker-grpc-resources/client.properties
  docker/docker-grpc-resources/multiple-clients-multiple-server/client1.properties
  docker/docker-grpc-resources/multiple-clients-multiple-server/client2.properties
  docker/docker-grpc-resources/multiple-clients-single-server/client1.properties
  docker/docker-grpc-resources/multiple-clients-single-server/client2.properties
  docker/docker-grpc-resources/performance-tests/single-client-ten-servers/client1.properties
  docker/docker-grpc-resources/performance-tests/ten-clients-single-server/client1.properties
  docker/docker-grpc-resources/performance-tests/ten-clients-single-server/client10.properties
  docker/docker-grpc-resources/performance-tests/ten-clients-single-server/client2.properties
  docker/docker-grpc-resources/performance-tests/ten-clients-single-server/client3.properties
  docker/docker-grpc-resources/performance-tests/ten-clients-single-server/client4.properties
  docker/docker-grpc-resources/performance-tests/ten-clients-single-server/client5.properties
  docker/docker-grpc-resources/performance-tests/ten-clients-single-server/client6.properties
  docker/docker-grpc-resources/performance-tests/ten-clients-single-server/client7.properties
  docker/docker-grpc-resources/performance-tests/ten-clients-single-server/client8.properties
  docker/docker-grpc-resources/performance-tests/ten-clients-single-server/client9.properties
  docs/client-configuration.md
  docs/new-client-server.md
  src/configs/client.properties
  src/configs/common-configuration.properties
  src/configs/multi-server-client.properties
  src/configs/multiple-clients-client1.properties
  src/configs/multiple-clients-client2.properties
  src/main/java/uk/gov/dbt/ndtp/federator/exceptions/AesCryptographicOperationException.java
  src/main/java/uk/gov/dbt/ndtp/federator/service/IdpTokenService.java
  src/main/java/uk/gov/dbt/ndtp/federator/service/IdpTokenServiceImpl.java
  src/main/java/uk/gov/dbt/ndtp/federator/utils/AesCryptoUtil.java
  src/main/java/uk/gov/dbt/ndtp/federator/utils/RedisUtil.java
  src/test/java/uk/gov/dbt/ndtp/federator/utils/AesCryptoUtilsTest.java
  src/test/java/uk/gov/dbt/ndtp/federator/utils/RedisUtilTest.java
  src/test/resources/client.properties
  src/test/resources/common-configuration.properties
Labels: documentation, feature

#47 Upgrade Java version and integrate ManagementNodeDataHandler
  .env
  .github/workflows/docker-ghcr.yml
  .github/workflows/maven.yml
  .github/workflows/release.yaml
  README.md
  docker/docker-grpc-resources/server.properties
  pom.xml
  src/configs/client.properties
  src/configs/server.properties
  src/main/java/uk/gov/dbt/ndtp/federator/FederatorClient.java
  src/main/java/uk/gov/dbt/ndtp/federator/FederatorServer.java
  src/main/java/uk/gov/dbt/ndtp/federator/client/connection/ConnectionProperties.java
  src/main/java/uk/gov/dbt/ndtp/federator/exceptions/ClientGRPCJobException.java
  src/main/java/uk/gov/dbt/ndtp/federator/jobs/DefaultJobSchedulerProvider.java
  src/main/java/uk/gov/dbt/ndtp/federator/jobs/Job.java
  src/main/java/uk/gov/dbt/ndtp/federator/jobs/JobSchedulerProvider.java
  src/main/java/uk/gov/dbt/ndtp/federator/jobs/handlers/ClientDynamicConfigJob.java
  src/main/java/uk/gov/dbt/ndtp/federator/jobs/handlers/ClientGRPCJob.java
  src/main/java/uk/gov/dbt/ndtp/federator/jobs/params/ClientGRPCJobParams.java
  src/main/java/uk/gov/dbt/ndtp/federator/jobs/params/JobParams.java
  src/main/java/uk/gov/dbt/ndtp/federator/jobs/params/RecurrentJobRequest.java
  src/main/java/uk/gov/dbt/ndtp/federator/management/ManagementNodeDataHandler.java
  src/main/java/uk/gov/dbt/ndtp/federator/model/dto/ProducerDTO.java
  src/main/java/uk/gov/dbt/ndtp/federator/utils/SSLUtils.java
  src/main/resources/producer-config.json
  src/test/java/uk/gov/dbt/ndtp/federator/FederatorClientTest.java
  src/test/java/uk/gov/dbt/ndtp/federator/integration/ManagementNodeIntegrationTest.java
  src/test/java/uk/gov/dbt/ndtp/federator/jobs/DefaultJobSchedulerProviderTest.java
  src/test/java/uk/gov/dbt/ndtp/federator/jobs/DefaultSchedulerProviderTest.java
  src/test/java/uk/gov/dbt/ndtp/federator/jobs/handlers/ClientDynamicConfigJobTest.java
  src/test/java/uk/gov/dbt/ndtp/federator/jobs/handlers/ClientGRPCJobTest.java
  src/test/java/uk/gov/dbt/ndtp/federator/management/ManagementNodeDataHandlerTest.java
  src/test/resources/test-jobrunr.properties
Labels: documentation, feature, actions, release

#62 DPAV-1425 Fixed Security label Filtering
  src/main/java/uk/gov/dbt/ndtp/federator/conductor/AbstractKafkaEventMessageConductor.java
  src/main/java/uk/gov/dbt/ndtp/federator/exceptions/LabelException.java
  src/main/java/uk/gov/dbt/ndtp/federator/filter/KafkaEventHeaderAttributeAccessFilter.java
  src/main/java/uk/gov/dbt/ndtp/federator/model/dto/AttributesDTO.java
  src/main/java/uk/gov/dbt/ndtp/federator/utils/HeaderUtils.java
  src/main/java/uk/gov/dbt/ndtp/federator/utils/SecurityLabelUtil.java
  src/test/java/uk/gov/dbt/ndtp/federator/conductor/AbstractKafkaEventMessageConductorTest.java
  src/test/java/uk/gov/dbt/ndtp/federator/filter/KafkaEventHeaderAttributeAccessFilterTest.java
  src/test/java/uk/gov/dbt/ndtp/federator/utils/HeaderUtilsTest.java
  src/test/java/uk/gov/dbt/ndtp/federator/utils/SecurityLabelUtilTest.java
Labels: feature

#64 fix(NON-REQ): close and finish grpc jobs if no further messages received
  src/main/java/uk/gov/dbt/ndtp/federator/FederatorService.java
  src/main/java/uk/gov/dbt/ndtp/federator/grpc/GRPCClient.java
  src/main/java/uk/gov/dbt/ndtp/federator/jobs/handlers/ClientGRPCJob.java
  src/main/java/uk/gov/dbt/ndtp/federator/service/IdpTokenServiceMtlsImpl.java
  src/test/java/uk/gov/dbt/ndtp/federator/jobs/handlers/ClientGRPCJobTest.java
Labels: fix
